"""update schemas

Revision ID: 9bae76476d33
Revises: a3985ccd5b6a
Create Date: 2026-02-04 22:53:26.595368

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '9bae76476d33'
down_revision: str | Sequence[str] | None = 'a3985ccd5b6a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
